### ISSUE TITLE
how to run?

### ISSUE THREAD

**Issue by kerner99** [Devilquest/BinanceOrderList#1]
Sorry I am completely new to coding and programming and so apologies for the stupid question, but how do I actually run the program?

**Comment by Devilquest** [comment]
You have to open it with visual studio and compile it.
Open visual studio
Open the project
Add dependences: Project menu -> Manage NuGet Packages... -> Browse and install Binance.Ney by JKorf and ClosedXML
Press F5 to compile and run it.
After the first run you can find an .exe file in the project folder: BinanceOrderList\bin\Debug

Also I've upload the compiled files in the releases section of this repository: https://github.com/Devilquest/BinanceOrderList/releases
